version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  solr:
    image: solr:latest
    ports:
      - "8983:8983"

  elasticsearch:
    image: elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - cluster.name=elastic-cluster
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - asos-elastic:/usr/share/elasticsearch/data

  lucene:
    image: ryanmeredith/lucene
    ports:
      - "5985:5985"

volumes:
  asos-elastic:
    driver: local
